Define ulimit and command in task definition.
toluna-terraform/terraform-aws-ecs pull request #13
Opened 2022-11-27 11:47 UTC by jonatan-berman-toluna

add the ability to define ulimits and command in the task definition.
If not defined in the ecs module the above will be null.

2022-11-27 13:35 UTC, Eli-Meitner requested changes
Please update the examples and run terraform-docs (to update readme)

2022-11-28 08:40 UTC, ShakedYosef approved these changes
Looks ok for me, but before you merge please update README and examples like Eli said.
Tnx.

2022-11-28 10:16 UTC, jonatan-berman-toluna commented
Updated readme and added example for ecs only use.

2022-11-28 10:48 UTC, Eli-Meitner approved these changes

2022-11-28 11:56 UTC, merged